name: Generate Daily TikTok Images

on:
  schedule:
    # Runs at 7:00 AM EST (12:00 PM UTC) every day
    # Adjust the time based on your timezone
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  generate-images:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate images
        run: |
          python generate_all_images.py

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-images-${{ steps.date.outputs.date }}
          path: generated_images/${{ steps.date.outputs.date }}/
          retention-days: 30

      - name: Commit and push images (optional)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add generated_images/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate images for ${{ steps.date.outputs.date }}" && git push)
        continue-on-error: true
